### ISSUE TITLE
(node:7788) UnhandledPromiseRejectionWarning: TypeError: API is not a constructor

### ISSUE THREAD

**Issue by Ytrap** [SoLoHK525/valorant-api#2]
Hi, the module d'ont work for me with this error : 
**(node:7788) UnhandledPromiseRejectionWarning: TypeError: API is not a constructor**
Thanks in advance.

**Comment by SoLoHK525** [comment]
It turns out I forgot to compile the code on npm.
Applied hotfix at version 0.3.4, update the package and retry.

Thanks 👍🏻
