### ISSUE TITLE
What about rate limiting?

### ISSUE THREAD

**Issue by Pyrolistical** [SoLoHK525/valorant-api#4]
The way this wrapper is designed, it hides the response so it would need to handle the rate limiting, but I don't see that in the code.

**Comment by SoLoHK525** [comment]
Error Handling will be added in the next version

**Comment by SoLoHK525** [comment]
Added error response handling in [v0.5.0](https://github.com/SoLoHK525/valorant-api/tree/e8f6334fa68d38faf5d8027a34833369228324d3)
